
# k8 will inform image address how k8 should run that image

kind: ConfigMap
apiVersion: v1

metadata:
  name: backend
  namesapce: expense
data:
  db_Host: mysql  

---------------------  


kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  namespace: expense
  labels:
    app: backend
    purpose: expense
    tier: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
      tier: app
  template:
    metadata:
      labels:
        app: backend 
        tier: app
        project: expense
        extra-key: extra-value   
    spec:
      containers:
      - name: backend
        image: prashanth3010/backend:v1.0

-----------------

apiVersion: v1
kind: Service          # here service will conect to pods
metadata:              # pop to pod communication build service we use 
  name: backend         # backend has to connnect msql pod , we have to estb
spec:
  selector:
    labels:
    app: backend
    purpose: expense
    tier: app
  ports:
  - protocol: TCP
    port: 8080 #service port
    targetPort: 8080 # traget port